# Generated by Django 4.2.2 on 2023-06-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='lliga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lliga.lliga'),
            preserve_default=False,
        ),
    ]
