# Generated by Django 4.2.2 on 2023-06-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0002_equip_lliga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='lliga',
        ),
        migrations.AddField(
            model_name='lliga',
            name='equips',
            field=models.ManyToManyField(to='lliga.equip'),
        ),
    ]
