# Generated by Django 4.2.2 on 2023-06-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0003_remove_equip_lliga_lliga_equips'),
    ]

    operations = [
        migrations.AddField(
            model_name='lliga',
            name='titol',
            field=models.CharField(default='BBVA', max_length=50),
            preserve_default=False,
        ),
    ]
