# Generated by Django 4.2.2 on 2023-06-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0004_lliga_titol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lliga',
            name='lliga',
        ),
    ]
