# Generated by Django 4.2.2 on 2023-06-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0005_remove_lliga_lliga'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='ciutat',
            field=models.CharField(default='ciutat', max_length=200),
            preserve_default=False,
        ),
    ]
