# Generated by Django 4.2.2 on 2023-06-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0006_equip_ciutat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='part',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
